cliente1 = input('digite seu nome: ')
idade1 = int(input('digite sua idade: '))
print ('cadastrado ', cliente1, idade1)
cliente2 = input('digite seu nome: ')
idade2 = int(input('digite sua idade: '))
print ('cadastrado ', cliente2, idade2)
cliente3 = input('digite seu nome: ')
idade3 = int(input('digite sua idade: '))
print ('cadastrado ', cliente3, idade3)
